### PR TITLE
Initial commit for linux

### PR DESCRIPTION
**Pull request by calvindo95**
I had started working on my own version of CPU monitoring for linux in C++, specifically for the performance. I saw this project and figured I'd share what I've made so far.

Steps to compile in linux dir:
```
mkdir build && cd build
cmake ..
cmake --build . -j4
```

This will create a sample binary called led_mon and a libcpu.so library file.
led_mon is just a sample executable that will print out cpu usage per core per line to stdout
libcpu.so can be imported into python so you can use the C/C++ library in python for performance reasons. The cpu_test.py file uses a python wrapper class to implement the C/C++ functions and can be run from linux dir with "python3 cpu_test.py"

Another thing to add, is that I'm trying to reduce dependencies by only using C++ and Python's standard libraries.
And idk what buildtools are needed as I probably already have everything installed on my computer.
Also I'll probably turn this specific linux code into it's own project, as my project direction is a bit different.

### CODE REVIEW

**Comment by calvindo95** [comment]
Also I don't use Windows or MacOS, so I'm pretty useless on those

**Comment by ayan20985** [comment]
Looks great! Is there any chance I could receive some confirmation of it working before I restructure the file naming and commit it to the main branch?

**Comment by ayan20985** [comment]
> Also I'll probably turn this specific linux code into it's own project, as my project direction is a bit different.

I think having this combined as one project might be a good idea, in the end I am aiming to have my Windows/MacOS build to be quite adaptable and generalized and I think our directions may be more aligned than at first glance.

**Review by ayan20985 — APPROVED** [review]
Looks good, ran some of my own tests in a Linux Virtual Machine.

**Pull request merged**
